### PR TITLE
donut-frontend-docs

### PR DESCRIPTION
**Pull request by AuraOfDivinity**
Added documentation for the donut [frontend part](https://docs.codeuino.org/documentation/).

### CODE REVIEW

**Comment by AuraOfDivinity** [comment]
@jaskirat2000 @vaibhavdaren @devesh-verma Kindly have a look and let me know if I have to add, remove or edit anything.

**Comment by jaskiratsingh2000** [comment]
It seema like you missed all the designs for frontend.
Try putting them and explaining it.
@SiddharthSimharaju can you please provide all the mockups to put that within doc?

**Comment by AuraOfDivinity** [comment]
@jaskirat2000 Thanks. I'll add them in as well!

**Comment by AuraOfDivinity** [comment]
@jaskirat2000  @devesh-verma  I have finalized the donut frontend documentation and made the requested changes. The documentation now includes a simple step by step guide on setting up the donut react app locally as well as a step by step guide on how to contribute to donut. If any more changes/additions to the documentation are required please do let me know!

**Review by jaskiratsingh2000 — APPROVED** [review]

**Pull request merged**
